---

- name: restart server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  sudo: true
  ignore_errors: true


- name: wait for server to restart
  local_action:
    wait_for
    host={{ inventory_hostname }}
    state=started
    port=22
    delay=15
    timeout=30
  sudo: false
