---

- name: install more tool on the Manager node
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - jq
    - curl
    - nginx

- name: install confd on the Manager node - get confd
  get_url: url=https://github.com/kelseyhightower/confd/releases/download/v0.11.0/confd-0.11.0-linux-amd64 dest=/usr/local/bin/confd mode=0744
  
- name: install confd on the Manager node - create confd config directory
  file: path=/etc/confd/conf.d state=directory recurse=yes owner=root group=root

- name: install confd on the Manager node - create confd template directory
  file: path=/etc/confd/templates state=directory recurse=yes owner=root group=root
  
- name: install confd on the Manager node - copy nginx template to confd config directory
  copy: src=nginx.template dest=/etc/confd/templates/nginx.template owner=root group=root mode=0644

- name: install confd on the Manager node - copy nginx template to confd config directory
  copy: src=nginx.toml dest=/etc/confd/conf.d/nginx.toml owner=root group=root mode=0644
  
- name: install confd on the Manager node - copy confd init script
  copy: src=confd dest=/etc/init.d/confd owner=root group=root mode=0755
  
- name: install confd on the Manager node - setup confd as linux service
  command: update-rc.d confd defaults 96 9
  
- name: install confd on the Manager node - copy haScript to /opt
  copy: src=haScripts dest=/opt owner=root group=root