---

- name: Check jenkins container status
  shell: "docker ps -a | grep '{{ app_name }}-{{ node_name }}-server' | cat"
  register: server_container_status

- name: Remove jenkins container with same name
  command: docker rm {{ app_name }}-{{ node_name }}-server
  when: server_container_status.stdout.find('Exited ') != -1
  register: server_container_removed

- name: allow permission for uid 1000
  file: path={{ jenkins_data_container_volume }}/{{ node_name }} state=directory owner=1000 group=1000

- name: Start new jenkins container
  command: >  
    docker run -d 
      --name {{ app_name }}-{{ node_name }}-server
      --env JENKINS_OPTS="--prefix=/jenkins-{{ node_name }}"
      -v {{ jenkins_data_container_volume }}/{{ node_name }}:/var/jenkins_home
      -p {{ jenkins_http_port }}:8080
      -p {{ jenkins_agent_port }}:50000
      {{ jenkins_docker_image }}
  when: (server_container_status.stdout.find('Up ') == -1)
