---

- name: install apt-https & CA certificates
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: add docker key
  apt_key: keyserver='{{ docker_key_repository }}' id='{{ docker_key_id }}' state=present

- name: creat docker repository
  apt_repository: repo='deb https://{{ docker_repository }} ubuntu-{{ ansible_distribution_release }} main' state=present update_cache=yes

- name: install docker
  apt: name=docker-engine state=present

- name: start docker
  service: name=docker state=started enabled=True
